### ISSUE TITLE
Compilation of "Bodies" example is b0rked w/ Xcode 14.3

### ISSUE THREAD

**Issue by alexlee002** [Lighter-swift/Examples#1]
It compiles failed on xcode14,  can anyone helps me?

**Comment by alexlee002** [comment]
the error now is:

```
sandbox-exec: sandbox_apply: Operation not permitted
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by helje5** [comment]
Hm, I can reproduce this. Not sure yet what's wrong here.

**Comment by helje5** [comment]
Looks like just the Bodies example fails, NorthwindSwiftUI works.

**Comment by helje5** [comment]
Maybe was b0rked by Apple as part  of this: https://support.apple.com/en-us/103012

**Comment by helje5** [comment]
Same in ~~Xcode 15.0.1~~ btw. Incorrect. Works w/ 15.0.1, I just had to clear DerivedData first.

**Comment by helje5** [comment]
Since I suspect that Apple is not going to fix Xcode 14.3, there is little we can do about this.

(the database could probably be moved to a local SPM project, but that would defeat the purpose of the sample)

**Comment by alexlee002** [comment]
> Looks like just the Bodies example fails, NorthwindSwiftUI works.

@helje5 yes, the  ` NorthwindSwiftUI` works and can be compiled and run, but it still get lots errors on Xcode IDE,  hot to fixit?

**Comment by alexlee002** [comment]
How to find the source code of  Northwind.Product ? How to generate it?

**Comment by helje5** [comment]
The source is generated from the database, that is what Lighter does. Errors shown initially should go away after doing the build.

**Comment by alexlee002** [comment]
errors hav't  gone away yet,  but the app can run!

<img width="846" alt="image" src="https://github.com/Lighter-swift/Examples/assets/576164/08a67f1a-9bcd-4cf5-84be-db0a17f3c3f3">
